//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFReservaVehiculos.Business.DataBaseModel
{
    using System;
    
    public enum EstadoReservaEnum : int
    {
        Activa = 1,
        Cancelada = 2
    }
}
