//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFReservaVehiculos.Business.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransaccionEntity
    {
        public string Id { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        public int UsuarioId { get; set; }
    }
}
