//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFReservaVehiculos.Business.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculoPorCiudadEntity
    {
        public int Id { get; set; }
        public int CantidadDisponible { get; set; }
        public int VehiculoId { get; set; }
        public int CiudadId { get; set; }
    
        public virtual CiudadEntity CiudadEntity { get; set; }
        public virtual VehiculoEntity VehiculoEntity { get; set; }
    }
}
