//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFReservaVehiculos.Business.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculoEntity
    {
        public int Id { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Puntaje { get; set; }
        public decimal PrecioPorDia { get; set; }
        public bool TieneDireccion { get; set; }
        public bool TieneAireAcon { get; set; }
        public int CantidadPuertas { get; set; }
        public string TipoCambio { get; set; }
    }
}
