//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumidorSoap.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.javapostsforlearning.arpit.org", ConfigurationName="ServiceReference1.HelloWorld")]
    public interface HelloWorld {
        
        // CODEGEN: Generating message contract since element name name from namespace http://webservices.javapostsforlearning.arpit.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        ConsumidorSoap.ServiceReference1.sayHelloWorldResponse sayHelloWorld(ConsumidorSoap.ServiceReference1.sayHelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumidorSoap.ServiceReference1.sayHelloWorldResponse> sayHelloWorldAsync(ConsumidorSoap.ServiceReference1.sayHelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sayHelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sayHelloWorld", Namespace="http://webservices.javapostsforlearning.arpit.org", Order=0)]
        public ConsumidorSoap.ServiceReference1.sayHelloWorldRequestBody Body;
        
        public sayHelloWorldRequest() {
        }
        
        public sayHelloWorldRequest(ConsumidorSoap.ServiceReference1.sayHelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.javapostsforlearning.arpit.org")]
    public partial class sayHelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public sayHelloWorldRequestBody() {
        }
        
        public sayHelloWorldRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sayHelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sayHelloWorldResponse", Namespace="http://webservices.javapostsforlearning.arpit.org", Order=0)]
        public ConsumidorSoap.ServiceReference1.sayHelloWorldResponseBody Body;
        
        public sayHelloWorldResponse() {
        }
        
        public sayHelloWorldResponse(ConsumidorSoap.ServiceReference1.sayHelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webservices.javapostsforlearning.arpit.org")]
    public partial class sayHelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sayHelloWorldReturn;
        
        public sayHelloWorldResponseBody() {
        }
        
        public sayHelloWorldResponseBody(string sayHelloWorldReturn) {
            this.sayHelloWorldReturn = sayHelloWorldReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWorldChannel : ConsumidorSoap.ServiceReference1.HelloWorld, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldClient : System.ServiceModel.ClientBase<ConsumidorSoap.ServiceReference1.HelloWorld>, ConsumidorSoap.ServiceReference1.HelloWorld {
        
        public HelloWorldClient() {
        }
        
        public HelloWorldClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWorldClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumidorSoap.ServiceReference1.sayHelloWorldResponse ConsumidorSoap.ServiceReference1.HelloWorld.sayHelloWorld(ConsumidorSoap.ServiceReference1.sayHelloWorldRequest request) {
            return base.Channel.sayHelloWorld(request);
        }
        
        public string sayHelloWorld(string name) {
            ConsumidorSoap.ServiceReference1.sayHelloWorldRequest inValue = new ConsumidorSoap.ServiceReference1.sayHelloWorldRequest();
            inValue.Body = new ConsumidorSoap.ServiceReference1.sayHelloWorldRequestBody();
            inValue.Body.name = name;
            ConsumidorSoap.ServiceReference1.sayHelloWorldResponse retVal = ((ConsumidorSoap.ServiceReference1.HelloWorld)(this)).sayHelloWorld(inValue);
            return retVal.Body.sayHelloWorldReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumidorSoap.ServiceReference1.sayHelloWorldResponse> ConsumidorSoap.ServiceReference1.HelloWorld.sayHelloWorldAsync(ConsumidorSoap.ServiceReference1.sayHelloWorldRequest request) {
            return base.Channel.sayHelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumidorSoap.ServiceReference1.sayHelloWorldResponse> sayHelloWorldAsync(string name) {
            ConsumidorSoap.ServiceReference1.sayHelloWorldRequest inValue = new ConsumidorSoap.ServiceReference1.sayHelloWorldRequest();
            inValue.Body = new ConsumidorSoap.ServiceReference1.sayHelloWorldRequestBody();
            inValue.Body.name = name;
            return ((ConsumidorSoap.ServiceReference1.HelloWorld)(this)).sayHelloWorldAsync(inValue);
        }
    }
}
